service: tutorversity 

provider:
  name: aws
  stage: dev
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:Scan
    - dynamodb:PutItem
    - dynamodb:GetItem
    - dynamodb:DeleteItem
    - dynamodb:Query
    - dynamodb:UpdateItem
    Resource:
    - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/tutorv-users*"]]
    - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/tutorv-questions*"]]

runtime: nodejs5.12
# runtime: nodejs6.10

functions:
  registerUser:
    handler: handler.registerUser
    events:
    - http:
        path: resgisteruser
        method: post
        cors: true
  auth:
    handler: handler.auth
    events:
    - http:
        path: auth
        method: post
        cors: true  
  newQuestion:
    handler: handler.newQuestion
    events:
    - http:
        path: newQuestion
        method: post
        cors: true
  getQuestions:
    handler: handler.getQuestions
    events:
    - http:
        path: getQuestions
        method: post
        cors: true
  getUserQuestions:
    handler: handler.getUserQuestions
    events:
    - http:
        path: getUserQuestions
        method: post
        cors: true
  logout:
    handler: handler.logout
    events:
    - http:
        path: logout
        method: post
        cors: true

  test:
    handler: handler.test
    events:
    - http:
        path: test
        method: post
        cors: true

resources:
  Resources:
    UserTable: 
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions: 
        - AttributeName: "email"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "email"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "tutorv-users"
    QuestionTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "tutorv-questions"
    MessagesTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "tutorv-messages"
